<?php

namespace AppBundle\Repository;

/**
 * ExternalProviderRawDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalProviderRawDataRepository extends \Doctrine\ORM\EntityRepository
{
}
