<?php

namespace AppBundle\Repository;

/**
 * ExternalProviderProductRawDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalProviderProductRawDataRepository extends \Doctrine\ORM\EntityRepository
{
}
