<?php

namespace AppBundle\Entity;

/**
 * ExternalProviderReviewRawDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalProviderReviewRawDataRepository extends \Doctrine\ORM\EntityRepository
{
}
