<?php

namespace AppBundle\Entity;

/**
 * ExternalProviderProcessedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalProviderProcessedDataRepository extends \Doctrine\ORM\EntityRepository
{
}
