<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * ExternalProviderReviewRawDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalProviderReviewRawDataRepository extends EntityRepository
{
    public function getProductFromReviewRawDataId($externalProductRawDataId) {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Product','p')
            ->innerJoin('AppBundle:ExternalProviderReviewRawData', 'rrd',
                Expr\Join::WITH, 'p.upc = rrd.upc')
            ->where('rrd.externalReviewRawDataId = :id')
            ->setParameter('id', $externalProductRawDataId)
            ->getQuery();
        return $query->getResult();
    }
}
