<?php

namespace AppBundle\Repository;

use AppBundle\AppBundle;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductSearchResults($searchString) {
        $searchString = '%'.$searchString.'%';
        return $this->getEntityManager()->createQueryBuilder()
            ->select('p.productName, p.productManufacturer, p.productRating, p.productImage, p.productCategory, p.isFeatured')
            ->from('AppBundle:Product', 'p')
            ->where('p.productName LIKE :searchString')
            ->andWhere('p.isActive = 1')
            ->setParameter('searchString', $searchString)
            ->orderBy('p.productName', 'desc')
            ->getQuery()
            ->getResult();
    }
}
