app:
    resource: '@AppBundle/Controller/'
    type: annotation

appBackend:
    resource: '@AppBundle/Controller/Backend/'
    type: annotation

appSwagger:
    resource: '@AppBundle/Resources/'
    type: annotation
