app:
    resource: '@AppBundle/Controller/'
    type: annotation

appBackend:
    resource: '@AppBundle/Controller/Backend/'
    type: annotation

ma27_api_key_authentication:
    resource: "@Ma27ApiKeyAuthenticationBundle/Resources/config/routing/routing.yml"
